### ISSUE TITLE
Missing files during testing model (translate.py)

### ISSUE THREAD

**Issue by bsantraigi** [cszmli/mirror-sigir#1]
Hi,
I followed your instructions to train a model, but when I am trying to test using translate.py, I am getting the following error. It seems it needs some extra files. Please let me know how to fix this error.

![image](https://user-images.githubusercontent.com/6783945/147687841-69093745-bf76-494b-a0ca-7223051af238.png)

**Comment by cszmli** [comment]
[DC_MMI](https://github.com/abaheti95/DC-NeuralConversation) data can be found [here](https://github.com/abaheti95/DC-NeuralConversation/tree/master/data/sif_data). You should also copy [the embeddings file](https://mega.nz/file/hd5VkYAY#eCAkC3Iw3Lsd9OWfzg-vZYKbZtdk8y73TAmo6CTnYkw) to the same folder. You may also want to change "/your/folder/folder" to your own data path.

**Comment by bsantraigi** [comment]
Thanks :)
